export default {
  GET_ALL_CODE_PROFILE: "GET_ALL_CODE_PROFILE",
  GET_ALL_CODE_PROFILE_STARTED: "GET_ALL_CODE_PROFILE_STARTED",
  GET_ALL_CODE_PROFILE_SUCCESS: "GET_ALL_CODE_PROFILE_SUCCESS",
  GET_ALL_CODE_PROFILE_NET_FAILED: "GET_ALL_CODE_PROFILE_NET_FAILED",
  GET_ALL_CODE_PROFILE_FAILED: "GET_ALL_CODE_PROFILE_FAILED",
  GET_CODE_PROFILE: "GET_CODE_PROFILE",
  GET_CODE_PROFILE_STARTED: "GET_CODE_PROFILE_STARTED",
  GET_CODE_PROFILE_SUCCESS: "GET_CODE_PROFILE_SUCCESS",
  GET_CODE_PROFILE_NET_FAILED: "GET_CODE_PROFILE_NET_FAILED",
  GET_CODE_PROFILE_FAILED: "GET_CODE_PROFILE_FAILED",
  DELETE_CODE_PROFILE: "DELETE_CODE_PROFILE",
  DELETE_CODE_PROFILE_STARTED: "DELETE_CODE_PROFILE_STARTED",
  DELETE_CODE_PROFILE_SUCCESS: "DELETE_CODE_PROFILE_SUCCESS",
  DELETE_CODE_PROFILE_NET_FAILED: "DELETE_CODE_PROFILE_NET_FAILED",
  DELETE_CODE_PROFILE_FAILED: "DELETE_CODE_PROFILE_FAILED"
};
