export default {
  SET_ID: "SET_ID",
  GET_DOCS_DATA: "GET_DOCS_DATA",
  GET_SINGLE_OBJ: "GET_SINGLE_OBJ",
  GET_FUNCTION_DEF: "GET_FUNCTION_DEF",
  GET_STATIC_MENU_CONTENT: "GET_STATIC_MENU_CONTENT"
};
