export default {
  FILE_UPLOAD: "FILE_UPLOAD",
  FILE_UPLOAD_STARTED: "FILE_UPLOAD_STARTED",
  FILE_UPLOAD_SUCCESS: "FILE_UPLOAD_SUCCESS",
  FILE_UPLOAD_NET_FAILED: "FILE_UPLOAD_NET_FAILED",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED"
};
