export default {
  FORGET_PASSWORD: "FORGET_PASSWORD",
  FORGET_PASSWORD_STARTED: "FORGET_PASSWORD_STARTED",
  FORGET_PASSWORD_SUCCESS: "FORGET_PASSWORD_SUCCESS",
  FORGET_PASSWORD_NET_FAILED: "FORGET_PASSWORD_NET_FAILED",
  FORGET_PASSWORD_FAILED: "FORGET_PASSWORD_FAILED"
};
