export default {
  GET_ANALYSIS: "GET_ANALYSIS",
  GET_ANALYSIS_STARTED: "GET_ANALYSIS_STARTED",
  GET_ANALYSIS_SUCCESS: "GET_ANALYSIS_SUCCESS",
  GET_ANALYSIS_NET_FAILED: "GET_ANALYSIS_NET_FAILED",
  GET_ANALYSIS_FAILED: "GET_ANALYSIS_FAILED"
};
