export default {
  GET_DOCUMENT: "GET_DOCUMENT",
  GET_DOCUMENT_STARTED: "GET_DOCUMENT_STARTED",
  GET_DOCUMENT_SUCCESS: "GET_DOCUMENT_SUCCESS",
  GET_DOCUMENT_NET_FAILED: "GET_DOCUMENT_NET_FAILED",
  GET_DOCUMENT_FAILED: "GET_DOCUMENT_FAILED"
};
