export default {
  RESET_PASSWORD: "RESET_PASSWORD",
  RESET_PASSWORD_STARTED: "RESET_PASSWORD_STARTED",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_NET_FAILED: "RESET_PASSWORD_NET_FAILED",
  RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED"
};
