export default {
  REGISTER_USER: "REGISTER_USER",
  REGISTER_USER_STARTED: "REGISTER_USER_STARTED",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_NET_FAILED: "REGISTER_USER_NET_FAILED",
  REGISTER_USER_FAILED: "REGISTER_USER_FAILED"
};
