export default {
  GET_TREE_NODE: "GET_TREE_NODE",
  GET_TREE_NODE_STARTED: "GET_TREE_NODE_STARTED",
  GET_TREE_NODE_SUCCESS: "GET_TREE_NODE_SUCCESS",
  GET_TREE_NODE_NET_FAILED: "GET_TREE_NODE_NET_FAILED",
  GET_TREE_NODE_FAILED: "GET_TREE_NODE_FAILED"
};
