export default {
    USER_INFO: "USER_INFO",
    USER_INFO_STARTED: "USER_INFO_STARTED",
    USER_INFO_SUCCESS: "USER_INFO_SUCCESS",
    USER_INFO_NET_FAILED: "USER_INFO_NET_FAILED",
    USER_INFO_FAILED: "USER_INFO_FAILED"
};
